/**
 * Wörter für Undercover, jedes mit drei Hinweisen für die Person, die das Wort
 * nicht kennt.
 *
 * Die Hinweise sind bewusst KEINE Synonyme: ein Ort, eine Situation oder eine
 * Eigenschaft. Mit einem ähnlichen Wort als Hinweis hatte die Runde nach zwei
 * Partien raus, dass man nur nach dem Nachbarbegriff suchen muss.
 *
 * Die Kategorie bleibt verborgen; aus ihr kommen nur die falschen Antworten
 * beim letzten Rateversuch, damit sie zum Hinweis passen könnten.
 */
export interface SecretWord {
  word: string;
  category: string;
  hints: [string, string, string];
}

export const WORDS: SecretWord[] = [
  { word: 'Kaffee', category: 'Getränke', hints: ['Büro', 'Morgen', 'bitter'] },
  { word: 'Bier', category: 'Getränke', hints: ['Stadion', 'Feierabend', 'Schaum'] },
  { word: 'Wein', category: 'Getränke', hints: ['Keller', 'Hochzeit', 'Jahrgang'] },
  { word: 'Sekt', category: 'Getränke', hints: ['Silvester', 'Anstoßen', 'prickelnd'] },
  { word: 'Tee', category: 'Getränke', hints: ['Erkältung', 'England', 'Beutel'] },
  { word: 'Cola', category: 'Getränke', hints: ['Kino', 'Zucker', 'Dose'] },
  { word: 'Pizza', category: 'Essen', hints: ['Italien', 'Lieferdienst', 'rund'] },
  { word: 'Döner', category: 'Essen', hints: ['Nachtbus', 'Spieß', 'Soße'] },
  { word: 'Pommes', category: 'Essen', hints: ['Freibad', 'Frittieren', 'Ketchup'] },
  { word: 'Sushi', category: 'Essen', hints: ['Fließband', 'Stäbchen', 'roh'] },
  { word: 'Brezel', category: 'Essen', hints: ['Oktoberfest', 'Knoten', 'salzig'] },
  { word: 'Spaghetti', category: 'Essen', hints: ['Gabel', 'Kochtopf', 'lang'] },
  { word: 'Popcorn', category: 'Essen', hints: ['Mikrowelle', 'Film', 'knallt'] },
  { word: 'Honig', category: 'Essen', hints: ['Bienen', 'Frühstück', 'klebrig'] },
  { word: 'Schokolade', category: 'Essen', hints: ['Ostern', 'Kakao', 'schmilzt'] },
  { word: 'Burger', category: 'Essen', hints: ['Grill', 'Brötchen', 'Fast Food'] },
  { word: 'Katze', category: 'Tiere', hints: ['Sofa', 'Internet', 'schnurren'] },
  { word: 'Hund', category: 'Tiere', hints: ['Gassi', 'Leine', 'treu'] },
  { word: 'Pinguin', category: 'Tiere', hints: ['Antarktis', 'Frack', 'watscheln'] },
  { word: 'Giraffe', category: 'Tiere', hints: ['Savanne', 'Flecken', 'Hals'] },
  { word: 'Hai', category: 'Tiere', hints: ['Film', 'Flosse', 'Zähne'] },
  { word: 'Pferd', category: 'Tiere', hints: ['Reiterhof', 'Hufeisen', 'Galopp'] },
  { word: 'Elefant', category: 'Tiere', hints: ['Zirkus', 'Gedächtnis', 'grau'] },
  { word: 'Spinne', category: 'Tiere', hints: ['Keller', 'Netz', 'acht'] },
  { word: 'Strand', category: 'Orte', hints: ['Handtuch', 'Sonnencreme', 'Sand'] },
  { word: 'Flughafen', category: 'Orte', hints: ['Koffer', 'Sicherheitskontrolle', 'Verspätung'] },
  { word: 'Krankenhaus', category: 'Orte', hints: ['Wartezimmer', 'Nachtschicht', 'weiß'] },
  { word: 'Kino', category: 'Orte', hints: ['Dunkelheit', 'Vorschau', 'Sessel'] },
  { word: 'Bibliothek', category: 'Orte', hints: ['Ausweis', 'Stille', 'Regal'] },
  { word: 'Fitnessstudio', category: 'Orte', hints: ['Januar', 'Spiegel', 'Schweiß'] },
  { word: 'Club', category: 'Orte', hints: ['Türsteher', 'Stempel', 'laut'] },
  { word: 'Friseur', category: 'Orte', hints: ['Umhang', 'Smalltalk', 'Schere'] },
  { word: 'Zoo', category: 'Orte', hints: ['Gehege', 'Schulausflug', 'Fütterung'] },
  { word: 'Kirche', category: 'Orte', hints: ['Glocke', 'Sonntag', 'Orgel'] },
  { word: 'Tankstelle', category: 'Orte', hints: ['Autobahn', 'Nachts', 'Zapfsäule'] },
  { word: 'Supermarkt', category: 'Orte', hints: ['Einkaufswagen', 'Kasse', 'Angebot'] },
  { word: 'Campingplatz', category: 'Orte', hints: ['Zelt', 'Mücken', 'Dusche'] },
  { word: 'Schwimmbad', category: 'Orte', hints: ['Sprungturm', 'Chlor', 'Bademeister'] },
  { word: 'Handy', category: 'Dinge', hints: ['Akku', 'Hosentasche', 'Display'] },
  { word: 'Regenschirm', category: 'Dinge', hints: ['Herbst', 'Garderobe', 'aufspannen'] },
  { word: 'Zahnbürste', category: 'Dinge', hints: ['Waschbecken', 'zweimal', 'Borsten'] },
  { word: 'Wecker', category: 'Dinge', hints: ['Nachttisch', 'Montag', 'klingelt'] },
  { word: 'Spiegel', category: 'Dinge', hints: ['Badezimmer', 'Märchen', 'glatt'] },
  { word: 'Kerze', category: 'Dinge', hints: ['Stromausfall', 'Geburtstag', 'Wachs'] },
  { word: 'Koffer', category: 'Dinge', hints: ['Gepäckband', 'Urlaub', 'Rollen'] },
  { word: 'Brille', category: 'Dinge', hints: ['Nase', 'Optiker', 'Gläser'] },
  { word: 'Schlüssel', category: 'Dinge', hints: ['Haustür', 'verlieren', 'Bund'] },
  { word: 'Fernbedienung', category: 'Dinge', hints: ['Sofakissen', 'Batterie', 'Knöpfe'] },
  { word: 'Luftballon', category: 'Dinge', hints: ['Kindergeburtstag', 'Helium', 'platzen'] },
  { word: 'Kopfhörer', category: 'Dinge', hints: ['U-Bahn', 'Kabel', 'Ohren'] },
  { word: 'Sonnenbrille', category: 'Dinge', hints: ['Sommer', 'Festival', 'dunkel'] },
  { word: 'Kühlschrank', category: 'Dinge', hints: ['Küche', 'Magnet', 'kalt'] },
  { word: 'Polizist', category: 'Berufe', hints: ['Uniform', 'Streife', 'Blaulicht'] },
  { word: 'Lehrer', category: 'Berufe', hints: ['Pausenhof', 'Tafel', 'Zeugnis'] },
  { word: 'Pilot', category: 'Berufe', hints: ['Cockpit', 'Durchsage', 'Uniform'] },
  { word: 'Koch', category: 'Berufe', hints: ['Mütze', 'Hitze', 'Rezept'] },
  { word: 'Zahnarzt', category: 'Berufe', hints: ['Bohrer', 'Angst', 'Liege'] },
  { word: 'Feuerwehrmann', category: 'Berufe', hints: ['Leiter', 'Sirene', 'Helm'] },
  { word: 'Kellner', category: 'Berufe', hints: ['Trinkgeld', 'Tablett', 'Schürze'] },
  { word: 'DJ', category: 'Berufe', hints: ['Plattenteller', 'Nacht', 'Wunsch'] },
  { word: 'Astronaut', category: 'Berufe', hints: ['Schwerelosigkeit', 'Rakete', 'Helm'] },
  { word: 'Tätowierer', category: 'Berufe', hints: ['Nadel', 'Motiv', 'Studio'] },
  { word: 'Fußball', category: 'Freizeit', hints: ['Sonntag', 'Tor', 'Trikot'] },
  { word: 'Karaoke', category: 'Freizeit', hints: ['Mikrofon', 'Schnaps', 'schief'] },
  { word: 'Zelten', category: 'Freizeit', hints: ['Lagerfeuer', 'Isomatte', 'Wald'] },
  { word: 'Skifahren', category: 'Freizeit', hints: ['Lift', 'Hütte', 'Winter'] },
  { word: 'Bowling', category: 'Freizeit', hints: ['Leihschuhe', 'Kegel', 'Bahn'] },
  { word: 'Angeln', category: 'Freizeit', hints: ['Geduld', 'See', 'Köder'] },
  { word: 'Yoga', category: 'Freizeit', hints: ['Matte', 'Atmung', 'dehnen'] },
  { word: 'Achterbahn', category: 'Freizeit', hints: ['Freizeitpark', 'Schlange', 'Looping'] },
  { word: 'Schach', category: 'Freizeit', hints: ['Brett', 'König', 'Denken'] },
  { word: 'Poker', category: 'Freizeit', hints: ['Pokerface', 'Chips', 'Karten'] },
  { word: 'Hochzeit', category: 'Anlässe', hints: ['Kleid', 'Torte', 'Ringe'] },
  { word: 'Geburtstag', category: 'Anlässe', hints: ['Kerzen', 'Geschenke', 'Lied'] },
  { word: 'Silvester', category: 'Anlässe', hints: ['Feuerwerk', 'Countdown', 'Vorsätze'] },
  { word: 'Weihnachten', category: 'Anlässe', hints: ['Baum', 'Familie', 'Dezember'] },
  { word: 'Junggesellenabschied', category: 'Anlässe', hints: ['Kostüm', 'Bauchladen', 'peinlich'] },
  { word: 'Abiball', category: 'Anlässe', hints: ['Anzug', 'Zeugnis', 'Rede'] },
  { word: 'Beerdigung', category: 'Anlässe', hints: ['schwarz', 'Blumen', 'Stille'] },
  { word: 'Oktoberfest', category: 'Anlässe', hints: ['Zelt', 'Dirndl', 'München'] },
  { word: 'Halloween', category: 'Anlässe', hints: ['Kürbis', 'Kostüm', 'Süßigkeiten'] },
  { word: 'Vorstellungsgespräch', category: 'Anlässe', hints: ['Lebenslauf', 'nervös', 'Anzug'] },
];
