/**
 * Kartenbibliothek für Lückenfüller.
 *
 * Alle Texte sind selbst geschrieben. Fremde Kartensätze scheiden aus: das
 * Vorbild verbietet in seiner eigenen FAQ ausdrücklich, seine Inhalte in einen
 * App Store einzureichen, auch in einer kostenlosen App.
 *
 * Form und Tabus, weil sie beim Ergänzen zählen:
 *
 * - Antwortkarten sind Nominalphrasen im NOMINATIV, klein beginnend, ohne
 *   Schlusspunkt. Sonst zerreißt der Kasus beim Einsetzen.
 * - Lückenkarten stellen die Lücke als Subjekt, als Gleichsetzung nach
 *   „ist/war", nach einem Doppelpunkt oder als Antwort auf eine Frage.
 *   Nie nach einer Präposition und nie als Objekt mitten im Satz.
 * - Die Lückenmarke ist genau `____`, und es sind so viele wie `pick`.
 * - Tabu in BEIDEN Stapeln: echte Personen, Herkunft, Religion, sexuelle
 *   Orientierung, Gewalt gegen Kinder, NS-Bezüge, Krankheit als Pointe.
 *
 * `cards.test.ts` prüft, was maschinell prüfbar ist.
 */

export interface BlackCard {
  text: string;
  /** Wie viele Antwortkarten die Lücke braucht. Fehlt = 1. */
  pick?: 2;
  /** Liegt nur im Stapel, wenn der Spicy-Schalter an ist. */
  spicy?: boolean;
}

export interface WhiteCard {
  text: string;
  spicy?: boolean;
}

export const BLACK: BlackCard[] = [
  // --- Normal ---
  { text: '____ hat diesen Abend gerettet.' },
  { text: '____ hat diesen Abend ruiniert.' },
  { text: 'Mein größter Fehler in diesem Jahr war ____.' },
  { text: 'Das Letzte, woran ich mich erinnere: ____' },
  { text: 'Was liegt morgens in meiner Jackentasche? ____' },
  { text: 'Der wahre Grund für meine Verspätung: ____' },
  { text: 'In meinem Kühlschrank wohnt seit Wochen ____.' },
  { text: 'Was steht auf dem Grabstein dieser Runde? ____' },
  { text: 'Mein Sternzeichen ist eigentlich ____.' },
  { text: 'Der schlechteste Name für eine Bar wäre ____.' },
  { text: 'Was hat mein Vermieter noch nicht bemerkt? ____' },
  { text: 'Der Elternabend drehte sich nur um eines: ____' },
  { text: 'Was mein Bewerbungsgespräch beendet hat? ____' },
  { text: 'Das neue Pflichtfach an jeder Schule heißt ____.' },
  { text: 'Was findet man unter meinem Bett? ____' },
  { text: 'Die ehrlichste Bewertung dieser Wohnung wäre ____.' },
  { text: 'Der Grund, warum ich nicht mehr eingeladen werde: ____' },
  { text: 'Mein Passwort ist seit Jahren ____.' },
  { text: 'Was hat der Paketbote heute gesehen? ____' },
  { text: 'Das Highlight meiner Jugend war ____.' },
  { text: 'In der Notaufnahme erklärte ich alles mit: ____' },
  { text: 'Mein Therapeut notiert bei jedem Termin ____.' },
  { text: 'Was den Sonntag rettet? ____' },
  { text: 'Was fehlt in jedem Erste-Hilfe-Kasten? ____' },
  { text: 'Meine Superkraft wäre ____.' },
  { text: 'Der schlimmste Preis bei einer Tombola ist ____.' },
  { text: 'Was ruiniert jedes Familienfoto? ____' },
  { text: 'Mein Chef nennt es Teamgeist. In Wahrheit ist es ____.' },
  { text: 'Das Geheimrezept meiner Oma ist ____.' },
  { text: 'Was hat die WG-Kasse dieses Jahr gekostet? ____' },
  { text: 'Auf meinem Klingelschild stünde am besten ____.' },
  { text: 'Der Höhepunkt jeder Betriebsfeier ist ____.' },
  { text: 'Was habe ich noch nie zurückgegeben? ____' },
  { text: 'Mein Fitnessstudio kennt mich als ____.' },
  { text: 'Die Autokorrektur macht daraus zuverlässig ____.' },
  { text: 'Was steht in meinem Browserverlauf ganz oben? ____' },
  { text: 'Der einzige Grund, morgens aufzustehen: ____' },
  { text: 'Beim Zahnarzt hilft mir nur ____.' },
  { text: 'Was gehört auf keinen Fall in die Spülmaschine? ____' },
  { text: 'Die Durchsage im Zug lautet heute: ____' },
  { text: 'Mein Lieblingsgeräusch ist ____.' },
  { text: 'Was hat noch nie funktioniert? ____' },
  { text: 'Das Motto meiner Zwanziger war ____.' },
  { text: 'Was liegt auf dem Beifahrersitz meines Autos? ____' },
  { text: 'Der schlimmste Moment beim Umzug ist ____.' },
  { text: 'Meine Ausrede für alles lautet inzwischen ____.' },
  { text: 'Was verschweigt jede Speisekarte? ____' },
  { text: 'Der Grund für meinen letzten Streit: ____' },
  { text: 'In meinem Kalender steht heute nur ____.' },
  { text: 'Was hat mich beim Camping wach gehalten? ____' },
  { text: 'Das erste, was Aliens über uns lernen: ____' },
  { text: 'Meine Rentenvorsorge ist ____.' },
  { text: 'Was steckt hinter dem Erfolg dieser Runde? ____' },
  { text: 'Der Klassiker auf jedem deutschen Balkon: ____' },
  { text: 'Was macht ein Montag mit einem Menschen? ____' },
  { text: 'Was mein Nachbar schriftlich beanstandet? ____' },
  { text: 'Das Beste am Erwachsenwerden ist ____.' },
  { text: 'Was hat meine Katze definitiv geplant? ____' },
  { text: 'Der Werbeslogan für dieses Getränk wäre ____.' },
  { text: 'In meinem letzten Traum kam ____ vor.' },
  { text: 'Was gehört verboten? ____' },
  { text: 'Die Wahrheit über meinen Kleiderschrank: ____' },
  { text: 'Was meinen Akku frisst? ____' },
  { text: 'Was fehlt diesem Abend noch? ____' },
  { text: 'Der Grund, warum ich schlecht schlafe: ____' },
  { text: 'Auf der Titelseite von morgen steht ____.' },
  { text: 'Was macht jeden Urlaub kaputt? ____' },
  { text: 'Mein Beitrag zum Weltfrieden wäre ____.' },
  { text: 'Der Inhalt meines Einkaufswagens sagt: ____' },
  { text: 'Was hat der Hausmeister im Keller gefunden? ____' },
  { text: 'Beim Vorstellungsgespräch verschweige ich ____.' },
  { text: 'Das Erste, was ich im Lotto kaufen würde: ____' },
  { text: 'Was steht in meiner Krankenakte? ____' },
  { text: 'Der wahre Grund für den Stau: ____' },
  { text: 'Meine Playlist heißt inzwischen ____.' },
  { text: 'Was hilft gegen einen Kater? ____' },
  { text: 'Am Ende bleibt immer nur ____.' },
  { text: 'Der Titel meiner Autobiografie: ____' },
  { text: 'Was passiert, wenn niemand hinschaut? ____' },
  { text: 'In meiner Schublade wartet seit Jahren ____.' },
  { text: '____ ist der Grund, warum wir nichts mehr planen.' },
  { text: 'Der neue Feiertag heißt ____ und dauert drei Tage.' },
  { text: 'Was steckt in der Überraschungstüte? ____' },
  { text: 'Mein Fahrlehrer sagte damals nur ____.' },
  { text: 'Was hat diese Gruppe zusammengebracht? ____' },
  { text: 'Der Grund, warum ich das Fenster geschlossen halte: ____' },

  // --- Normal, zwei Lücken ---
  { text: '____ plus ____ ergibt den perfekten Sonntag.', pick: 2 },
  { text: 'Erst kam ____, dann kam ____.', pick: 2 },
  { text: 'Statt ____ gab es dieses Jahr ____.', pick: 2 },
  { text: '____ ist das neue ____.', pick: 2 },
  { text: 'Mein Tag: erst ____, dann ____', pick: 2 },
  { text: '____ trifft ____, und niemand überlebt es.', pick: 2 },

  // --- Spicy: nur mit Schalter ---
  { text: 'Der schlimmste Ort für ein erstes Date ist ____.', spicy: true },
  { text: 'Was tötet jede Stimmung sofort? ____', spicy: true },
  { text: 'Meine Dating-Bio, wenn ich ehrlich wäre: ____', spicy: true },
  { text: 'Was hat mein Ex definitiv behalten? ____', spicy: true },
  { text: 'Der Grund, warum es beim zweiten Date nicht klappte: ____', spicy: true },
  { text: 'Was gehört nicht ins Schlafzimmer? ____', spicy: true },
  { text: 'Die ehrlichste Antwort auf „Wie war ich?": ____', spicy: true },
  { text: 'Was habe ich noch nie jemandem erzählt? ____', spicy: true },
  { text: 'Mein Suchverlauf ist zu neunzig Prozent ____.', spicy: true },
  { text: 'Was riecht man in dieser Wohnung zuerst? ____', spicy: true },
  { text: 'Der schlimmste Fund im Hotelzimmer war ____.', spicy: true },
  { text: 'Was passiert nach dem sechsten Bier? ____', spicy: true },
  { text: 'Die rote Flagge, über die ich hinwegsehe: ____', spicy: true },
  { text: 'Was habe ich im Vollrausch bestellt? ____', spicy: true },
  { text: 'Was mein Körper gerade meldet: ____', spicy: true },
  { text: 'Was hat die Nachbarin durch die Wand gehört? ____', spicy: true },
  { text: 'Der peinlichste Grund für einen Arztbesuch: ____', spicy: true },
  { text: 'Was landet nach dieser Runde auf dem Teppich? ____', spicy: true },
  { text: 'Die schlimmste Nachricht um drei Uhr nachts: ____', spicy: true },
  { text: 'Was macht diese Toilette gerade durch? ____', spicy: true },
  { text: 'Mein Tinder-Profil verschweigt ____.', spicy: true },
  { text: 'Was habe ich beim Sport verloren? ____', spicy: true },
  { text: 'Der Grund, warum wir nicht mehr über Silvester reden: ____', spicy: true },
  { text: 'Was habe ich im Taxi zurückgelassen? ____', spicy: true },
  { text: 'Die wahre Zutat in diesem Cocktail ist ____.', spicy: true },
  { text: 'Was steht in meiner gelöschten Galerie? ____', spicy: true },
  { text: 'Der schlimmste Spitzname, den ich je hatte: ____', spicy: true },
  { text: 'Was höre ich, kurz bevor mir schlecht wird? ____', spicy: true },
  { text: 'Mein Morgen danach ist ____.', spicy: true },
  { text: 'Was hat der Türsteher gesehen? ____', spicy: true },
  { text: 'Der Grund für den Fleck auf der Couch: ____', spicy: true },
  { text: 'Was gehört in jede ehrliche Hochzeitsrede? ____', spicy: true },
  { text: 'Die letzte Nachricht an meinen Ex lautete ____.', spicy: true },
  { text: 'Was habe ich gerade heimlich weggeräumt? ____', spicy: true },
  { text: 'Was auf keinem Familienessen passieren darf: ____', spicy: true },
  { text: 'Was hält diese Beziehung zusammen? ____', spicy: true },
  { text: 'Mein Geheimnis vor dieser Runde ist ____.', spicy: true },
  { text: 'Was habe ich noch nie gewaschen? ____', spicy: true },

  // --- Spicy, zwei Lücken ---
  { text: 'Erst ____, dann ____, dann die Reue.', pick: 2, spicy: true },
  { text: '____ und ____ sind eine schlechte Kombination.', pick: 2, spicy: true },
  { text: 'Mein Date: erst ____, am Ende ____', pick: 2, spicy: true },
  { text: '____ und ____ trennt genau ein Bier.', pick: 2, spicy: true },
  { text: 'Ich bereue ____, aber nicht ____.', pick: 2, spicy: true },
  { text: 'Was ich im Bett nie wieder ausprobiere: ____', spicy: true },
  { text: 'Mein Safeword ist ____.', spicy: true },
  { text: 'Der wahre Grund für die Scheidung: ____', spicy: true },
  { text: 'Was hat der Nachbar durch die Wand gehört? ____', spicy: true },
  { text: 'Mein geheimer Fetisch: ____', spicy: true },
  { text: 'Was liegt in meinem Nachttisch? ____', spicy: true },
  { text: 'Das Beste am One-Night-Stand war ____.', spicy: true },
  { text: 'Was sagt man besser nicht beim Sex? ____', spicy: true },
  { text: 'Beim Dreier lief alles gut, bis ____ dazukam.', spicy: true },
  { text: 'Mein ehrliches Datingprofil: ____ und ____.', pick: 2, spicy: true },
  { text: '____ ist nichts für das erste Mal.', spicy: true },
  { text: 'Was turnt mich komplett ab? ____', spicy: true },
  { text: 'Mein Porno hätte nur eine Szene: ____', spicy: true },
  { text: 'Was hat die Putzfrau unter dem Bett gefunden? ____', spicy: true },
];

export const WHITE: WhiteCard[] = [
  // --- Normal ---
  { text: 'ein halber Döner in der Manteltasche' },
  { text: 'der Ex, der immer noch mitliest' },
  { text: 'drei Wochen alter Kartoffelsalat' },
  { text: 'ein Anruf bei der eigenen Mutter' },
  { text: 'die letzte Bahn um 0:47 Uhr' },
  { text: 'ein Kaufvertrag über ein Wasserbett' },
  { text: 'zwei Promille vor dem Frühstück' },
  { text: 'ein Tattoo mit Rechtschreibfehler' },
  { text: 'eine WhatsApp-Gruppe mit vierzig Leuten' },
  { text: 'ein ungeöffneter Brief vom Finanzamt' },
  { text: 'die Oma, die heimlich Tinder benutzt' },
  { text: 'ein Schnappschuss ohne Vorwarnung' },
  { text: 'die Playlist aus der neunten Klasse' },
  { text: 'ein Sofa, das nicht durch die Tür passt' },
  { text: 'die Rechnung vom letzten Abend' },
  { text: 'ein Pflasterstein im Handgepäck' },
  { text: 'sieben ungelesene Sprachnachrichten' },
  { text: 'ein Pinguin im Nachtbus' },
  { text: 'das Passwort auf einem gelben Zettel' },
  { text: 'ein Kollege, der Excel liebt' },
  { text: 'die Ruhe vor dem Elternabend' },
  { text: 'der Onkel, der beim Grillen philosophiert' },
  { text: 'eine Playlist namens „Nur kurz"' },
  { text: 'der Pfandautomat, der alles ablehnt' },
  { text: 'ein Sechserpack lauwarmes Bier' },
  { text: 'die zweite Meinung des Internets' },
  { text: 'ein Einhorn mit Alkoholproblem' },
  { text: 'das Fahrrad, das nie abgeschlossen war' },
  { text: 'die Google-Bewertung „Nie wieder“' },
  { text: 'ein Seepferdchen-Abzeichen mit 34' },
  { text: 'der Mitbewohner, der nur in Unterhose kocht' },
  { text: 'die Kollegin aus der Buchhaltung' },
  { text: 'ein Zettel mit „Bin gleich zurück"' },
  { text: 'ein Waschbär im Hochzeitskleid' },
  { text: 'die Diashow vom Kreuzfahrturlaub der Eltern' },
  { text: 'zwölf Euro Trinkgeld aus Versehen' },
  { text: 'ein Kater, der bis Dienstag hält' },
  { text: 'das Bild an der Wand, das niemand mag' },
  { text: 'ein Clown, der sich im Datum geirrt hat' },
  { text: 'die Ausrede mit dem schlechten Netz' },
  { text: 'die Mama-Nachricht mit elf Emojis' },
  { text: 'ein Kumpel, der „nur kurz“ Krypto erklärt' },
  { text: 'ein Rückruf, der nie kommt' },
  { text: 'ein Hochzeitsredner mit Powerpoint' },
  { text: 'die Frikadelle aus der Hosentasche' },
  { text: 'das Gefühl, etwas vergessen zu haben' },
  { text: 'eine Tiefkühlpizza ohne Ofen' },
  { text: 'ein Tanzkurs mit dem eigenen Vater' },
  { text: 'ein Sofa voller Kekskrümel' },
  { text: 'die Erinnerung an den Zivildienst' },
  { text: 'der Typ, der auf jeder Party Gitarre spielt' },
  { text: 'zwei Stunden Warteschleife' },
  { text: 'eine Wurst mit Vorgeschichte' },
  { text: 'ein Vertrag mit 24 Monaten Laufzeit' },
  { text: 'ein Schwan, der mich persönlich hasst' },
  { text: 'ein Kaugummi unter dem Tisch' },
  { text: 'der Hausmeister mit Generalschlüssel' },
  { text: 'die Sprachnachricht vom Opa mit Nasenatmung' },
  { text: 'das Foto vom Betriebsausflug' },
  { text: 'ein Wikinger-Kostüm im Büro' },
  { text: 'die Frage nach dem Bausparvertrag' },
  { text: 'ein leerer Akku um 19 Uhr' },
  { text: 'der Junggesellenabschied in Bratislava' },
  { text: 'ein Toastbrot mit dem Gesicht vom Chef' },
  { text: 'eine Geburtstagsrede, die aus dem Ruder lief' },
  { text: 'ein Klingelton aus dem Jahr 2007' },
  { text: 'die Schwiegermutter am Telefon' },
  { text: 'ein Bademeister mit Midlife-Crisis' },
  { text: 'der Sitzplatz neben der Toilette' },
  { text: 'eine Steuererklärung im Juli' },
  { text: 'das Trikot vom falschen Verein' },
  { text: 'das Arschgeweih meiner Tante' },
  { text: 'die Stimme aus dem Navigationsgerät' },
  { text: 'ein Sonnenbrand mit Trägerabdruck' },
  { text: 'das Schnitzel vom Vortag' },
  { text: 'eine Reklamation ohne Kassenbon' },
  { text: 'der Wecker am Feiertag' },
  { text: 'ein Selfie mit geschlossenen Augen' },
  { text: 'ein Möwenangriff auf die Pommes' },
  { text: 'ein Gutschein, der gestern ablief' },
  { text: 'der Kumpel, der plötzlich Veganer ist' },
  { text: 'eine Videokonferenz ohne Ton' },
  { text: 'der Termin um sieben Uhr morgens' },
  { text: 'eine Luftmatratze mit leisem Pfeifen' },
  { text: 'ein Fünf-Liter-Fass zum Frühstück' },
  { text: 'ein Hemd, das nur gebügelt gut aussieht' },
  { text: 'die Hochzeit, bei der keiner das Paar kennt' },
  { text: 'eine Katze auf der Tastatur' },
  { text: 'der Stromausfall mitten im Film' },
  { text: 'ein Kollege mit Mundgeruch' },
  { text: 'ein Ziegenyoga-Kurs am Sonntag' },
  { text: 'ein Kassenzettel über 1,20 Euro' },
  { text: 'der Gerichtsvollzieher mit Humor' },
  { text: 'eine Nachricht mit drei Punkten' },
  { text: 'der Feiertag, der auf Sonntag fällt' },
  { text: 'ein Leberkäse im Handgepäck' },
  { text: 'die Reifenpanne auf der Landstraße' },
  { text: 'ein Verwandter mit starker Meinung' },
  { text: 'das Handy im Waschbecken' },
  { text: 'eine Terminabsage per Sprachnachricht' },
  { text: 'die Karaoke-Version von „Atemlos“' },
  { text: 'ein Klassentreffen nach zwanzig Jahren' },
  { text: 'ein Hamster mit Instagram-Account' },
  { text: 'ein Zug voller Fußballfans' },
  { text: 'das letzte Stück Kuchen' },
  { text: 'eine Beschwerde in Schönschrift' },
  { text: 'der Opa, der jeden Tag Techno hört' },
  { text: 'ein Nacktscanner am Flughafen' },
  { text: 'die Frage „Wie geht es dir wirklich?"' },
  { text: 'ein Bewerbungsfoto von 2011' },
  { text: 'ein Dirndl beim Bewerbungsgespräch' },
  { text: 'eine Runde Schnaps auf Kosten des Hauses' },
  { text: 'der Kollege, der immer Recht hat' },
  { text: 'ein Aufzug zwischen zwei Etagen' },
  { text: 'die Rechnung geteilt durch elf' },
  { text: 'die Vokuhila-Phase meines Vaters' },
  { text: 'das WLAN-Passwort der Schwiegereltern' },
  { text: 'eine Impfbescheinigung im Schuhkarton' },
  { text: 'ein Furz im vollen Aufzug' },
  { text: 'ein Fahrradschloss ohne Schlüssel' },
  { text: 'der Poolnudel-Kampf im Hotel' },
  { text: 'ein Anruf von unterdrückter Nummer' },
  { text: 'das Kleingedruckte im Mietvertrag' },
  { text: 'eine Runde Halli Galli um Mitternacht' },
  { text: 'ein Heiratsantrag auf der Stadionleinwand' },
  { text: 'ein Gruppenfoto ohne mich' },
  { text: 'ein Brief an mein zwölfjähriges Ich' },
  { text: 'ein Praktikum ohne Bezahlung' },
  { text: 'die Nachbarin mit dem Fernglas' },
  { text: 'ein Kaktus als einziger Freund' },
  { text: 'der Schrank, den ich allein aufgebaut habe' },
  { text: 'ein Sonntagsspaziergang mit Ansage' },
  { text: 'die Playlist des Taxifahrers' },
  { text: 'ein Handtuch auf der Liege um sechs Uhr' },
  { text: 'das Trinkgeld in Münzen' },
  { text: 'eine Kaution, die nie zurückkam' },
  { text: 'der Zettel an der Windschutzscheibe' },
  { text: 'der Lieferfahrer, der meinen Vornamen kennt' },
  { text: 'eine Schlägerei auf dem Dorffest' },
  { text: 'ein Kühlschrank voller Senf' },
  { text: 'ein Mettigel mit Sonnenbrille' },
  { text: 'das Sparschwein mit Einbruchspuren' },
  { text: 'der Sitznachbar mit lauten Kopfhörern' },
  { text: 'ein Goldfisch-Begräbnis mit Trauerrede' },
  { text: 'die Bratwurst am Bahnhof' },
  { text: 'ein Buch, das ich nie zu Ende lese' },
  { text: 'die Tante, die nach dem Gehalt fragt' },
  { text: 'eine Bahnansage ohne Erklärung' },
  { text: 'ein Schlumpf-Tattoo am Knöchel' },
  { text: 'ein Zettel mit fremder Handschrift' },
  { text: 'die Chipstüte voller Luft' },
  { text: 'ein Feuermelder mit leerer Batterie' },
  { text: 'der Weihnachtspullover im Juli' },
  { text: 'eine Bewerbung, die ich nie abgeschickt habe' },
  { text: 'der Nachbar mit Bohrmaschine' },
  { text: 'ein Gartenzwerg mit Mittelfinger' },
  { text: 'die Fritteuse der WG' },
  { text: 'die Status-Weisheiten meines Onkels' },
  { text: 'das Handtuch, das nach drei Tagen riecht' },
  { text: 'eine Warteschlange im Bürgeramt' },
  { text: 'der Termin beim Amt in acht Wochen' },
  { text: 'ein Balkon mit Blick auf die Mülltonnen' },
  { text: 'die Katze, die nur beim Nachbarn frisst' },
  { text: 'ein Toaster mit Eigenleben' },
  { text: 'das Duschgel des Mitbewohners' },
  { text: 'eine Nachricht von kurz nach drei' },
  { text: 'der Schluck aus der falschen Flasche' },
  { text: 'ein Abend ohne Netz' },
  { text: 'die Frage nach dem Kinderwunsch' },
  { text: 'ein Sofa vom Sperrmüll' },
  { text: 'das Lieblingslied der Nachbarn' },
  { text: 'ein Selbstgespräch im Baumarkt' },
  { text: 'der Wasserschaden im Bad' },
  { text: 'ein Gruppenchat um Mitternacht' },
  { text: 'die Rechnung für den Notdienst' },
  { text: 'das Horoskop, das mein Leben steuert' },
  { text: 'ein Ex, der jetzt Coach ist' },
  { text: 'eine Runde Karaoke ohne Publikum' },
  { text: 'der Kollege mit dem Bluetooth-Headset' },
  { text: 'ein Sturz auf der Treppe' },
  { text: 'die Kiste im Keller, die niemand öffnet' },
  { text: 'ein Freitag, der sich wie Mittwoch anfühlt' },
  { text: 'ein Rentner auf dem E-Scooter' },
  { text: 'eine Fahrkarte für die falsche Zone' },
  { text: 'der Kaugummi im Haar' },
  { text: 'ein Abend, an den sich niemand erinnert' },
  { text: 'die Playlist auf Zufall' },
  { text: 'die Brusthaare von Onkel Günther' },
  { text: 'das Buffet um kurz vor Schluss' },
  { text: 'eine Sprachnachricht über neun Minuten' },
  { text: 'eine Gurkenmaske im Videocall' },
  { text: 'ein Wochenende ohne Plan' },
  { text: 'das Gemüsefach als Endlager' },
  { text: 'der Kumpel, der nie seine Runde zahlt' },
  { text: 'der Schlüssel im abgeschlossenen Auto' },
  { text: 'ein Kaffee für vier Euro achtzig' },
  { text: 'die Kollegin, die immer friert' },
  { text: 'ein Vortrag mit vierzig Folien' },
  { text: 'das Geräusch eines platzenden Reifens' },
  { text: 'eine Fahrt ohne Fahrschein' },
  { text: 'ein Bierbauch mit eigenem Namen' },
  { text: 'ein Handwerker, der zurückruft' },
  { text: 'die Ruhe nach dem letzten Gast' },
  { text: 'ein Kuchen, der in der Mitte roh ist' },
  { text: 'das Auto des Fahrlehrers' },
  { text: 'eine Fernbeziehung mit Zugbindung' },
  { text: 'die Katze, die mich beim Duschen beobachtet' },
  { text: 'ein Hund in Designerklamotten' },
  { text: 'die Suche nach dem Ladekabel' },
  { text: 'ein Klingelstreich um zwei Uhr' },
  { text: 'das Fischbrötchen am Hafen' },
  { text: 'eine Sitzung, die eine Mail hätte sein können' },
  { text: 'der Schlager-Remix um vier Uhr' },
  { text: 'ein Männerschnupfen mit Testament' },
  { text: 'die Frage, wer fahren muss' },
  { text: 'das Kleid, das nur im Laden passte' },
  { text: 'eine Runde Skat mit drei Hausregeln' },
  { text: 'der Geburtstag, den ich vergessen habe' },
  { text: 'ein Rasen, der nie gemäht wird' },
  { text: 'ein Ticket ohne Sitzplatzreservierung' },
  { text: 'das Ende einer Serie nach acht Staffeln' },
  { text: 'die Mama, die „lol“ für Liebe hält' },
  { text: 'der Rest im Weinglas von gestern' },
  { text: 'die Erinnerung an den ersten Job' },
  { text: 'das Netzteil, das immer warm ist' },
  { text: 'eine Fahrradtour mit Gegenwind' },
  { text: 'der Kollege, der nie Kaffee kocht' },
  { text: 'ein Vertrag, den niemand gelesen hat' },
  { text: 'ein Pony auf dem Balkon' },
  { text: 'ein Schulausflug in den Regen' },
  { text: 'das Ampelrot an einer leeren Kreuzung' },
  { text: 'ein Klappstuhl mit Mordabsicht' },
  { text: 'der Dorfdisco-DJ im Ruhestand' },
  { text: 'ein Feuerzeug, das nie zurückkommt' },
  { text: 'die Frage nach dem Kassenbon' },
  { text: 'eine Hochzeitstorte auf dem Boden' },
  { text: 'das Bett im Hostel ganz oben' },
  { text: 'die Wurstplatte als Liebeserklärung' },
  { text: 'der Regenschirm im Bus' },
  { text: 'ein Grill, der nicht anspringt' },
  { text: 'die Nachricht „Wir müssen reden"' },
  { text: 'ein Sonntagabend im November' },
  { text: 'eine Bank, die zwei Prozent verlangt' },
  { text: 'der Zug mit fünfzig Minuten Verspätung' },
  { text: 'ein Taubenschwarm mit Racheplan' },
  { text: 'ein Abendessen bei den Schwiegereltern' },
  { text: 'das letzte Bier im Kasten' },
  { text: 'der Hund, der nur mich anbellt' },
  { text: 'ein Zettel mit einer Telefonnummer' },
  { text: 'die Ausrede „Ich war krank"' },
  { text: 'das Profilbild mit Fisch in der Hand' },
  { text: 'das Kaugummi unter der Schuhsohle' },
  { text: 'eine Kaffeefahrt mit Busfahrt' },
  { text: 'eine Mittagspause im Solarium' },
  { text: 'ein Rezept mit vierzehn Zutaten' },
  { text: 'die Frage, ob noch jemand Hunger hat' },
  { text: 'der Kollege, der im Videocall aufs Klo geht' },
  { text: 'eine Reise mit Zwischenstopp in Frankfurt' },
  { text: 'der Papierstau im Drucker' },
  { text: 'ein Zahnarzt, der beim Bohren Fragen stellt' },
  { text: 'ein Balkon voller Zigarettenstummel' },
  { text: 'eine Postkarte, die nach dem Urlaub ankommt' },
  { text: 'der Nachbar, der immer zuhause ist' },
  { text: 'ein Wecker mit Schlummertaste' },
  { text: 'die Rechnung für den Abschleppdienst' },
  { text: 'das Schweigen im Aufzug' },
  { text: 'die Hafermilch-Debatte beim Brunch' },
  { text: 'der Schuhkarton mit Fotos' },
  { text: 'ein Salat mit zu viel Dressing' },
  { text: 'die Wand, die nie gestrichen wurde' },
  { text: 'ein Anruf während des Essens' },
  { text: 'das Wechselgeld auf dem Tresen' },
  { text: 'eine Fahrt mit dem Nachtbus' },
  { text: 'der Karton mit Weihnachtsschmuck' },
  { text: 'ein Kalender vom letzten Jahr' },
  { text: 'die Tür, die nach innen aufgeht' },
  { text: 'ein Handy im Flugmodus' },
  { text: 'das Brot vom Vortag' },
  { text: 'eine Diskussion über Fußball' },
  { text: 'der Schrank, in dem alles verschwindet' },
  { text: 'ein Feiertag mitten in der Woche' },
  { text: 'die Klingel, die zu laut ist' },
  { text: 'ein Buch mit Eselsohren' },
  { text: 'das Formular in dreifacher Ausfertigung' },
  { text: 'eine Party, die um neun endet' },
  { text: 'ein Regenbogen über der Autobahn' },
  { text: 'ein Tinder-Match mit dem Grundschullehrer' },
  { text: 'ein Rucksack voller Pfandflaschen' },
  { text: 'eine Uhr im Wartezimmer' },
  { text: 'der Tag nach dem Zahltag' },
  { text: 'ein Wasserkocher mit Kalk' },
  { text: 'die Frage nach dem Studienabschluss' },
  { text: 'ein Sonnenschirm bei Wind' },
  { text: 'eine Mail mit dem Betreff „Dringend"' },
  { text: 'der Stuhl mit dem kurzen Bein' },
  { text: 'ein Abend vor dem offenen Kühlschrank' },
  { text: 'die Zahnbürste des Mitbewohners' },
  { text: 'ein Ersatzschlüssel unter der Fußmatte' },
  { text: 'das Getränk ohne Kohlensäure' },
  { text: 'eine Fahrt ohne Musik' },
  { text: 'der Zettel am Kühlschrank' },
  { text: 'ein Kuchen aus der Packung' },
  { text: 'die Bahn, die früher fährt' },
  { text: 'das Konzert in der dritten Reihe' },
  { text: 'eine Tasse Tee um Mitternacht' },
  { text: 'der Aschenbecher auf dem Balkon' },
  { text: 'ein Termin am Freitagnachmittag' },
  { text: 'die Frage, wer das bezahlt' },
  { text: 'ein Hemd mit Kaffeefleck' },
  { text: 'das Fahrrad im vierten Stock' },
  { text: 'eine Nacht auf der Isomatte' },
  { text: 'der Rest vom Buffet' },
  { text: 'ein Zug ohne Bordbistro' },
  { text: 'die Steckdose hinter dem Schrank' },
  { text: 'das Lied, das nicht aus dem Kopf geht' },
  { text: 'eine Tüte Chips als Abendessen' },
  { text: 'der Kollege mit dem Geburtstagskuchen' },
  { text: 'ein Sitzsack aus der Studienzeit' },
  { text: 'die Fahrt zum Flughafen um vier Uhr' },
  { text: 'ein Regal ohne Dübel' },
  { text: 'das Kartenspiel ohne Anleitung' },
  { text: 'eine Wohnungsbesichtigung mit vierzig Leuten' },
  { text: 'der Wasserhahn, der tropft' },
  { text: 'ein Ausflug in den Baumarkt' },
  { text: 'die Nachricht von der Bank' },
  { text: 'ein Kaffee aus dem Automaten' },
  { text: 'eine Rechnung mit Mahngebühr' },
  { text: 'der Ventilator im Großraumbüro' },
  { text: 'ein Schlüsselbund mit acht Schlüsseln' },
  { text: 'die Vorspeise, die satt macht' },
  { text: 'das Ende einer langen Woche' },
  { text: 'eine Runde Mensch ärgere dich nicht' },
  { text: 'ein Kalenderspruch zum Montag' },
  { text: 'die Frage nach dem Mietvertrag' },
  { text: 'ein Schnitzel größer als der Teller' },
  { text: 'das Radio im Nachbarzimmer' },
  { text: 'eine Wanderung mit den falschen Schuhen' },
  { text: 'der Schneematsch vor der Haustür' },
  { text: 'ein Handschuh ohne Partner' },
  { text: 'die Bahnfahrt mit Umstieg in Hannover' },
  { text: 'ein Zimmer ohne Fenster' },
  { text: 'eine Nachricht ohne Punkt am Ende' },
  { text: 'der Karton, der zu klein ist' },
  { text: 'ein Sofa in Beige' },
  { text: 'die Schokolade im Nachttisch' },
  { text: 'ein Nachbar mit Aquarium' },
  { text: 'eine Bewerbung mit Standardanschreiben' },
  { text: 'der Stapel Post auf dem Tisch' },
  { text: 'ein Grillabend ohne Kohle' },
  { text: 'die Tüte Gummibärchen im Handschuhfach' },
  { text: 'ein Schluck kaltes Wasser' },
  { text: 'das Klopfen an der Wand' },
  { text: 'eine Frage im falschen Moment' },
  { text: 'der Herd, der noch an ist' },
  { text: 'ein Regenmantel in Gelb' },
  { text: 'die Kaffeepause um halb elf' },
  { text: 'ein Bügeleisen mit Dampfstoß' },
  { text: 'das Pfand auf der Kiste' },
  { text: 'eine Runde Uno mit Hausregeln' },
  { text: 'der Zettel im Fahrradkorb' },
  { text: 'ein Sonntag im Bett' },
  { text: 'die Nachricht an die falsche Gruppe' },
  { text: 'ein Handy ohne Schutzhülle' },
  { text: 'eine Tür, die von selbst zufällt' },
  { text: 'der Weg zurück zum Auto' },
  { text: 'ein Kühlschrank mit einer Zitrone' },
  { text: 'die Aussicht vom Parkhausdach' },
  { text: 'ein Abend mit dem falschen Film' },
  { text: 'das Trinkgeld, das niemand sieht' },
  { text: 'eine Rolle Klebeband ohne Anfang' },
  { text: 'der Schrank voller Marmeladengläser' },
  { text: 'ein Zug im Ersatzverkehr' },
  { text: 'die Fritteuse der Wohngemeinschaft' },

  // --- Spicy: nur mit Schalter ---
  { text: 'ein Kondom im Handschuhfach', spicy: true },
  { text: 'die Nachricht an den Ex um vier Uhr', spicy: true },
  { text: 'ein Ausschlag an ungünstiger Stelle', spicy: true },
  { text: 'ein Dildo im Handgepäck', spicy: true },
  { text: 'ein Fleck, der sich nicht erklären lässt', spicy: true },
  { text: 'die Suchleiste im privaten Fenster', spicy: true },
  { text: 'ein Anruf beim Ex nach zwei Flaschen', spicy: true },
  { text: 'der Vibrator, der beim Essen anspringt', spicy: true },
  { text: 'eine Tattoo-Entscheidung um drei Uhr', spicy: true },
  { text: 'ein Paar Handschellen ohne Schlüssel', spicy: true },
  { text: 'ein Date, das die Rechnung teilen will', spicy: true },
  { text: 'ein Dreier, der als Spieleabend begann', spicy: true },
  { text: 'ein Selfie, das nie jemand sehen sollte', spicy: true },
  { text: 'das Geräusch aus dem Nebenzimmer', spicy: true },
  { text: 'eine Beichte am Küchentisch', spicy: true },
  { text: 'die Nachbarn, die schon wieder laut Sex haben', spicy: true },
  { text: 'ein Kondom von 2014 im Geldbeutel', spicy: true },
  { text: 'der Sex im Zelt bei Dauerregen', spicy: true },
  { text: 'das Handy des Partners ohne Sperre', spicy: true },
  { text: 'eine Sprachnachricht, die zu weit ging', spicy: true },
  { text: 'der Inhalt meines Nachttischs', spicy: true },
  { text: 'ein Nacktfoto in der Familiengruppe', spicy: true },
  { text: 'das Sexspielzeug in der Spülmaschine', spicy: true },
  { text: 'ein Ausrutscher auf der Betriebsfeier', spicy: true },
  { text: 'das Kissen, das nach fremdem Parfüm riecht', spicy: true },
  { text: 'ein One-Night-Stand, der zum Frühstück bleibt', spicy: true },
  { text: 'die Pornosammlung auf dem Familien-PC', spicy: true },
  { text: 'ein Knutschfleck beim Vorstellungsgespräch', spicy: true },
  { text: 'ein Nachbar, der zu viel gehört hat', spicy: true },
  { text: 'das Kleidungsstück auf dem Balkongeländer', spicy: true },
  { text: 'der Swingerclub neben dem Finanzamt', spicy: true },
  { text: 'ein Walk of Shame in High Heels', spicy: true },
  { text: 'ein Zettel mit einem fremden Namen darauf', spicy: true },
  { text: 'die Peitsche aus dem Erotikshop', spicy: true },
  { text: 'ein Fußabdruck an der Decke', spicy: true },
  { text: 'eine Liebesschaukel ohne Dübel', spicy: true },
  { text: 'ein Nippelpiercing, das am Pulli hängt', spicy: true },
  { text: 'ein Stringtanga im Wäschekorb der Eltern', spicy: true },
  { text: 'das Kamasutra für Fortgeschrittene', spicy: true },
  { text: 'ein Orgasmus, der die Nachbarn weckt', spicy: true },
  { text: 'das Gespräch über Verhütung beim Frühstück', spicy: true },
  { text: 'der Latexanzug, der nicht mehr abgeht', spicy: true },
  { text: 'der Moment, in dem das Licht angeht', spicy: true },
  { text: 'ein Sexting mit Autokorrektur', spicy: true },
  { text: 'die Nachricht „Bist du noch wach?"', spicy: true },
  { text: 'die Rollenspielnacht als Steuerprüfer', spicy: true },
  { text: 'ein Pärchen, das auf der Party verschwindet', spicy: true },
  { text: 'das Gleitgel in der Sonnencremeflasche', spicy: true },
  { text: 'ein Striptease zu Helene Fischer', spicy: true },
  { text: 'die Sexszene im Film mit den Eltern', spicy: true },
  { text: 'die Frage nach dem Beziehungsstatus', spicy: true },
  { text: 'ein Blick in die eigene Galerie', spicy: true },
  { text: 'ein Penis-Strohhalm vom Junggesellenabschied', spicy: true },
  { text: 'ein Erotikroman im Wartezimmer', spicy: true },
  { text: 'die Bettgeschichte, die alle mitgehört haben', spicy: true },
  { text: 'ein Quickie auf der Hochzeitstoilette', spicy: true },
  { text: 'das Sexvideo, das in der Cloud landete', spicy: true },
  { text: 'ein Stripper mit Rückenproblemen', spicy: true },
  { text: 'ein Fußfetisch für Crocs', spicy: true },
  { text: 'ein Handtuch, das jemand anders benutzt hat', spicy: true },
  { text: 'der nackte Hintern auf dem Bürokopierer', spicy: true },
  { text: 'ein Ex, der im Bett immer „Danke“ sagte', spicy: true },
  { text: 'das Foto vom Junggesellenabschied', spicy: true },
  { text: 'eine Diskussion über Treue nach Mitternacht', spicy: true },
  { text: 'das Stöhnen aus dem Hotelzimmer nebenan', spicy: true },
  { text: 'die Nachricht, die nicht mehr zu löschen war', spicy: true },
  { text: 'ein Fleck auf dem Sofa der Eltern', spicy: true },
  { text: 'ein Sexspielzeug mit Bluetooth', spicy: true },
  { text: 'der Blowjob-Shot an der Bar', spicy: true },
  { text: 'der Griff nach dem falschen Handy', spicy: true },
  { text: 'ein Callboy mit Kundenkarte', spicy: true },
  { text: 'die Nacktsauna mit den Kollegen', spicy: true },
  { text: 'ein Kuss, der nie geplant war', spicy: true },
  { text: 'ein Pornotitel über die eigene Stadt', spicy: true },
  { text: 'eine Beichte im Treppenhaus', spicy: true },
  { text: 'die Unterhose am Kronleuchter', spicy: true },
  { text: 'ein Bett, in dem drei Leute liegen', spicy: true },
  { text: 'ein Bett, das unter uns zusammenbrach', spicy: true },
  { text: 'die Morgenlatte im Familienurlaub', spicy: true },
  { text: 'ein Busenblitzer auf dem Firmenfoto', spicy: true },
  { text: 'das Kondom, das spurlos verschwunden ist', spicy: true },
  { text: 'eine Affäre mit dem Postboten', spicy: true },
  { text: 'der Sexshop-Gutschein von Oma', spicy: true },
  { text: 'ein Vorspiel, das 40 Sekunden dauert', spicy: true },
  { text: 'die Stellung, die Physiotherapie braucht', spicy: true },
  { text: 'ein Seitensprung im Gartenhaus', spicy: true },
  { text: 'das Safeword „Bratkartoffel“', spicy: true },
  { text: 'ein Fesselspiel mit Paketband', spicy: true },
  { text: 'die Nacktbilder im Ordner „Steuer 2019“', spicy: true },
  { text: 'ein Hintern mit Tattoo vom Ex', spicy: true },
  { text: 'ein Foto mit fremden Menschen', spicy: true },
  { text: 'das Knistern einer Kondompackung im Dunkeln', spicy: true },
  { text: 'ein Tinder-Date mit dem eigenen Chef', spicy: true },
  { text: 'der Porno mit echter Handlung', spicy: true },
  { text: 'ein Tanz auf dem Tisch', spicy: true },
  { text: 'ein Penisfoto ohne Vorwarnung', spicy: true },
  { text: 'der Sex auf der Waschmaschine beim Schleudern', spicy: true },
  { text: 'ein Erotik-Hörbuch im Autoradio', spicy: true },
  { text: 'eine Nachricht an die Chefin um zwei Uhr', spicy: true },
  { text: 'die Handschellen im Nachttisch der Eltern', spicy: true },
  { text: 'ein nackter Hintern am Busfenster', spicy: true },
  { text: 'die Frage, ob das jemand gefilmt hat', spicy: true },
  { text: 'die Sexpause für die Pizza', spicy: true },
  { text: 'das Gespräch mit der eigenen Mutter darüber', spicy: true },
  { text: 'ein Liebesbrief voller schmutziger Reime', spicy: true },
  { text: 'das Sexspielzeug beim Zoll', spicy: true },
  { text: 'ein Zungenkuss beim Flaschendrehen', spicy: true },
  { text: 'die Ex, die im Bett Pokémon aufzählte', spicy: true },
  { text: 'ein Karton mit Erinnerungen an den Ex', spicy: true },
  { text: 'das Wiedersehen im Treppenhaus', spicy: true },
  { text: 'ein schlüpfriger Spruch der Schwiegermutter', spicy: true },
  { text: 'der Schlüssel, der von innen steckt', spicy: true },
  { text: 'ein Pflaster an der Stirn', spicy: true },
  { text: 'die Frage nach der letzten Beziehung', spicy: true },
  { text: 'ein Blick auf die Kontobewegungen', spicy: true },
  { text: 'das Handy im Waschbecken der Bar', spicy: true },
  { text: 'eine Abfuhr in aller Öffentlichkeit', spicy: true },
  { text: 'der Freund, der alles weitererzählt', spicy: true },
  { text: 'ein Abend, der mit Wasser hätte enden sollen', spicy: true },
  { text: 'die Jacke, die jemand anders trug', spicy: true },
  { text: 'ein Anruf von der Versicherung', spicy: true },
  { text: 'das Bier zum Frühstück', spicy: true },
  { text: 'eine Ausrede für den Montag', spicy: true },
  { text: 'der Kühlschrank ohne Wasser', spicy: true },
  { text: 'ein Kopfkissen, das nicht mir gehört', spicy: true },
  { text: 'die Nummer, die ich nie gespeichert habe', spicy: true },
  { text: 'ein Blick in den Spiegel um sieben Uhr', spicy: true },
  { text: 'das Ergebnis einer langen Nacht', spicy: true },
  { text: 'eine Erklärung, die niemand glaubt', spicy: true },
  { text: 'ein Schluck aus der Pfandflasche', spicy: true },
  { text: 'die Rückfahrt im Morgengrauen', spicy: true },
  { text: 'ein Freund, der Fotos gemacht hat', spicy: true },
  { text: 'das Trinkspiel mit den Schwiegereltern', spicy: true },
  { text: 'eine Wette über die eigene Würde', spicy: true },
  { text: 'der Griff zur letzten Flasche', spicy: true },
  { text: 'ein Fleck auf dem Hemd der Chefin', spicy: true },
  { text: 'die Nacht, über die niemand spricht', spicy: true },
  { text: 'ein Sturz vor der Haustür', spicy: true },
  { text: 'das Gefühl am nächsten Nachmittag', spicy: true },
  { text: 'eine Runde Shots auf Kredit', spicy: true },
  { text: 'der Weg ins Bett über vier Stufen', spicy: true },
  { text: 'ein Handtuch als Bettdecke', spicy: true },
  { text: 'die Frage, wer aufräumt', spicy: true },
  { text: 'ein Kuss zum Abschied, der zu lang war', spicy: true },
  { text: 'das Bett des Mitbewohners', spicy: true },
  { text: 'eine Nachricht mit zu vielen Herzen', spicy: true },
  { text: 'der Moment, in dem die Musik ausgeht', spicy: true },
  { text: 'ein Anruf bei der Mutter um Mitternacht', spicy: true },
  { text: 'die Erkenntnis, dass alle zugehört haben', spicy: true },
  { text: 'das Duschen um vier Uhr morgens', spicy: true },
  { text: 'eine Umarmung, die zu lange dauert', spicy: true },
  { text: 'der Fund unter dem Sofakissen', spicy: true },
  { text: 'ein Kühlschrank voller angebrochener Flaschen', spicy: true },
  { text: 'die Wette, wer als Letzter steht', spicy: true },
  { text: 'ein Fußmarsch von acht Kilometern', spicy: true },
  { text: 'das Foto auf dem Sperrbildschirm', spicy: true },
  { text: 'eine Diskussion über Ex-Partner', spicy: true },
  { text: 'der Rest im Glas vom Vorabend', spicy: true },
  { text: 'ein Klingeln an der falschen Tür', spicy: true },
  { text: 'die Nacht im Wohnzimmer der Eltern', spicy: true },
  { text: 'ein Versprechen unter Alkoholeinfluss', spicy: true },
  { text: 'das Erwachen im falschen Stadtteil', spicy: true },
  { text: 'eine Rechnung mit vier Runden darauf', spicy: true },
  { text: 'der Blick der Kollegen am Montag', spicy: true },
  { text: 'ein Schlafsack im Flur', spicy: true },
  { text: 'die Frage, ob das gerade passiert', spicy: true },
  { text: 'das Bier, das jemand anders bezahlt hat', spicy: true },
  { text: 'eine Nacht ohne Handyempfang', spicy: true },
  { text: 'der Geschmack von warmem Wodka', spicy: true },
  { text: 'ein Kuss vor der versammelten Runde', spicy: true },
  { text: 'die Tür, die offen stand', spicy: true },
  { text: 'ein Rest Sekt in der Blumenvase', spicy: true },
  { text: 'das Ende einer Freundschaft um vier Uhr', spicy: true },
  { text: 'eine Beichte, die niemand hören wollte', spicy: true },
  { text: 'der Karton mit Pizzaresten im Bett', spicy: true },
  { text: 'ein Schuh, der im Club geblieben ist', spicy: true },
  { text: 'die Notiz-App vom Vorabend', spicy: true },
  { text: 'ein Streit über die Musikauswahl', spicy: true },
  { text: 'das Bad, das jemand renovieren muss', spicy: true },
  { text: 'eine Frage, die zu ehrlich beantwortet wurde', spicy: true },
  { text: 'der Weg zurück ohne Jacke', spicy: true },
  { text: 'die Wahrheit über gestern Abend', spicy: true },
  { text: 'ein Klingelschild, das nicht stimmt', spicy: true },
  { text: 'das Gefühl beim Aufstehen', spicy: true },
  { text: 'eine Wette, die ich verloren habe', spicy: true },
  { text: 'der Rest der Nacht im Treppenhaus', spicy: true },
  { text: 'ein Handtuch über dem Rauchmelder', spicy: true },
  { text: 'die Nachricht an alle statt an einen', spicy: true },
  { text: 'ein Auge, das zugeschwollen ist', spicy: true },
  { text: 'das Trinkgeld, das viel zu hoch war', spicy: true },
  { text: 'eine Nacht, die niemand geplant hat', spicy: true },
  { text: 'der Anruf, der auf dem Band gelandet ist', spicy: true },
  { text: 'ein Bademantel als Straßenkleidung', spicy: true },
  { text: 'die Diskussion über den letzten Zug', spicy: true },
  { text: 'ein Kühlschrank, der nur Sekt enthält', spicy: true },
  { text: 'das Kinn auf der Tischplatte', spicy: true },
  { text: 'eine Nachricht voller Tippfehler', spicy: true },
  { text: 'der Versuch, den Schlüssel zu treffen', spicy: true },
  { text: 'ein Tanzpartner ohne Namen', spicy: true },
  { text: 'die Rechnung vom Lieferdienst um drei Uhr', spicy: true },
  { text: 'ein Anruf, der zwei Stunden dauerte', spicy: true },
  { text: 'die Suche nach dem zweiten Schuh', spicy: true },
  { text: 'ein Bett, das sich noch dreht', spicy: true },
  { text: 'der Sekt, der schon offen war' },
  { text: 'ein Stuhl aus dem Partykeller' },
  { text: 'die Kaffeetasse mit Lippenstift' },
  { text: 'das Dschungelcamp als Karriereplan' },
  { text: 'ein Selfie-Stick auf der Beerdigung der Katze' },
  { text: 'eine Kiste Wasser im dritten Stock' },
  { text: 'der Nachbar, der mit der Nagelschere mäht' },
  { text: 'eine Kuh, die schlauer guckt als ich' },
  { text: 'die Fahrt mit einem Leihwagen' },
  { text: 'das Karaoke-Duett mit dem Chef' },
  { text: 'ein Trampolin und drei Promille' },
  { text: 'der Onkel, der Zaubertricks vorführt' },
  { text: 'der Stapel ungewaschener Teller' },
  { text: 'eine Bauchtasche voller Kurze' },
  { text: 'das Fitnessstudio-Abo seit 2019 ungenutzt' },
  { text: 'ein Ordner namens „Sonstiges“' },
  { text: 'ein Kumpel, der immer „Digga“ sagt' },
  { text: 'eine Postkarte ohne Absender' },
  { text: 'der Stift, der nicht mehr schreibt' },
  { text: 'ein Sonntag mit Verwandtenbesuch' },
  { text: 'der Nackt-Schneeengel um drei Uhr', spicy: true },
  { text: 'ein Sexshop-Einkauf mit Kundenberatung', spicy: true },
  { text: 'die Webcam, die doch an war', spicy: true },
  { text: 'ein Vibrator mit leerem Akku', spicy: true },
];