import { createCardGame, type CardDef } from '../card-engine/createCardGame';
import { meta } from './meta';

const WAHRHEIT: CardDef[] = [
  { text: 'Was war dein peinlichster Moment in der Schule?', heat: 1 },
  { text: 'Welchen Song hörst du heimlich in Dauerschleife?', heat: 1 },
  { text: 'Wie viele ungelesene Nachrichten hast du gerade? Zeig es her.', heat: 1 },
  { text: 'Was ist die größte Lüge, die du deinen Eltern erzählt hast?', heat: 1 },
  { text: 'Welche App würdest du niemandem hier zeigen?', heat: 1 },
  { text: 'Was war dein schlimmster Modefehler?', heat: 1 },
  { text: 'Wen im Raum würdest du bei einer Zombie-Apokalypse zuerst opfern?', heat: 1 },
  { text: 'Was hast du zuletzt gegoogelt? Wortwörtlich.', heat: 1 },
  { text: 'Welches Talent hast du, von dem hier niemand weiß?', heat: 1 },
  { text: 'Was ist dein größter ungelöster Kindheitstraum?', heat: 1 },
  { text: 'Welchen Film hast du behauptet zu mögen, obwohl du ihn hasst?', heat: 1 },
  { text: 'Wie lange hast du am längsten nicht geduscht?', heat: 1 },
  { text: 'Was war das Peinlichste, das du im Suff gemacht hast?', heat: 2 },
  { text: 'Wen aus dieser Runde hättest du beinahe mal angeschrieben?', heat: 2 },
  { text: 'Was war deine schlimmste Date-Erfahrung?', heat: 2 },
  { text: 'Wie viel Geld hast du für den größten Blödsinn ausgegeben?', heat: 2 },
  { text: 'Welches Gerücht über dich stimmt tatsächlich?', heat: 2 },
  { text: 'Hast du schon mal jemanden aus der Runde gestalkt? Sag wen.', heat: 2 },
  { text: 'Was ist die lächerlichste Ausrede, mit der du dich rausgeredet hast?', heat: 2 },
  { text: 'Welche Person hier wäre in einer Alternativwelt dein Typ?', heat: 2 },
  { text: 'Was war dein bislang größter Fail bei der Arbeit oder im Studium?', heat: 2 },
  { text: 'Bei welcher Sache bist du deutlich schlechter, als du zugibst?', heat: 2 },
  { text: 'Wen aus der Runde würdest du daten, wenn du müsstest?', heat: 3 },
  { text: 'Was ist dein größter Beziehungs-Fail?', heat: 3 },
  { text: 'Welchen Ex würdest du noch mal treffen – und warum?', heat: 3 },
  { text: 'Was war das Verrücktes, das du je aus Verliebtheit gemacht hast?', heat: 3 },
  { text: 'Welches Geheimnis würde deine Familie am meisten schockieren?', heat: 3 },
  { text: 'Wen aus der Runde findest du am schwersten einzuschätzen? Und warum?', heat: 3 },
  { text: 'Was ist der eine Text, den du bereust abgeschickt zu haben?', heat: 3 },
  { text: 'Welche Meinung hast du, die hier alle gegen dich aufbringen würde?', heat: 3 },
].map((c) => ({ ...c, mode: 'wahrheit' }) as CardDef);

/** Nur im Stapel, wenn der Spicy-Modus an ist. */
const WAHRHEIT_SPICY: CardDef[] = [
  { text: 'Was war dein bester Kuss – und was hat ihn so gut gemacht?' },
  { text: 'Wen aus dieser Runde hättest du beinahe mal geküsst?' },
  { text: 'Was ist dein größter Turn-off beim Flirten?' },
  { text: 'Was war deine peinlichste Situation beim Anbaggern?' },
  { text: 'Wo war der ungewöhnlichste Ort, an dem du geknutscht hast?' },
  { text: 'Was findest du an einer Person zuerst attraktiv – ehrlich?' },
  { text: 'Welcher Mensch ist dein absoluter Freifahrtschein?' },
  { text: 'Was ist die kühnste Nachricht, die du je verschickt hast? Zusammenfassung reicht.' },
  { text: 'Welchen Ex würdest du heute noch mal treffen – und warum genau?' },
  { text: 'Was war das Verrückteste, das du aus Verliebtheit gemacht hast?' },
  { text: 'Hast du dich schon mal in eine Freundin oder einen Freund verliebt?' },
  { text: 'Welche Eigenschaft an dir hat schon mal jemanden verjagt?' },
  { text: 'Was ist dein Dealbreaker, über den niemand hinwegkommt?' },
  { text: 'Wen aus deinem Umfeld hast du schon mal heimlich vermisst?' },
].map((c) => ({ ...c, mode: 'wahrheit', heat: 3, spicy: true }) as CardDef);

const PFLICHT: CardDef[] = [
  { text: 'Sprich die nächsten drei Runden nur im Flüsterton.', heat: 1 },
  { text: 'Mach eine überzeugende Wettervorhersage für morgen – live und mit Gesten.', heat: 1 },
  { text: 'Lass die Person links von dir deine nächste Nachricht schreiben.', heat: 1 },
  { text: 'Imitiere jemanden aus der Runde. Wer sich erkennt, trinkt.', minPlayers: 3, heat: 1 },
  { text: 'Halte 30 Sekunden lang Blickkontakt mit der Person gegenüber. Wer zuerst lacht, trinkt.', heat: 1 },
  { text: 'Erfinde einen Werbespot für den Gegenstand, der dir am nächsten liegt.', heat: 1 },
  { text: 'Sing den Refrain des letzten Songs, den du gehört hast.', heat: 1 },
  { text: 'Mach 10 Kniebeugen – die Runde zählt laut mit.', heat: 1 },
  { text: 'Sprich bis zu deinem nächsten Zug in der dritten Person über dich.', heat: 1 },
  { text: 'Tausche für zwei Runden ein Kleidungsstück mit deinem rechten Nachbarn.', heat: 1 },
  { text: 'Erzähl eine 30-Sekunden-Geschichte, die komplett erfunden ist. Die Runde rät: wahr oder gelogen?', heat: 1 },
  { text: 'Lies deine letzte gesendete Nachricht laut vor.', heat: 2 },
  { text: 'Zeig das letzte Foto in deiner Galerie.', heat: 2 },
  { text: 'Ruf eine zufällige Person aus deinen Kontakten an und sing ihr Happy Birthday.', heat: 2 },
  { text: 'Lass die Runde eine Story für dich posten. Du darfst nicht schauen.', heat: 2 },
  { text: 'Mach eine ehrliche Ansage an eine Person in der Runde – etwas Nettes, das du nie gesagt hast.', heat: 2 },
  { text: 'Tanze 20 Sekunden ohne Musik, als wärst du auf einem Festival.', heat: 2 },
  { text: 'Lass dich von der Runde neu frisieren. Bleibt für den Rest des Abends.', heat: 2 },
  { text: 'Sprich die nächsten zwei Runden nur in Fragen.', heat: 2 },
  { text: 'Bis zu deinem nächsten Zug bist du der Butler der Runde.', heat: 2 },
  { text: 'Poste ein unvorteilhaftes Selfie in eine Gruppe deiner Wahl.', heat: 3 },
  { text: 'Lass die Runde deinen Kontaktnamen für eine Person ändern. Für immer.', heat: 3 },
  { text: 'Schreib deinem letzten Match ein Kompliment. Die Runde formuliert es.', heat: 3 },
  { text: 'Verrate das Passwort-Muster deiner Handy-Sperre – nicht das Passwort, das Muster.', heat: 3 },
  { text: 'Erzähl die peinlichste Geschichte, die du kennst – über dich.', heat: 3 },
  { text: 'Lass die Person gegenüber drei Minuten lang dein Handy halten. Sie darf nichts öffnen – nur halten. Vertrauen ist alles.', heat: 3 },
  { text: 'Mach ein Kompliment an jede Person in der Runde. Keine Wiederholungen.', heat: 3 },
].map((c) => ({ ...c, mode: 'pflicht' }) as CardDef);

const PFLICHT_SPICY: CardDef[] = [
  { text: 'Mach der Person rechts von dir ein Kompliment, das du sonst nie aussprechen würdest.' },
  { text: 'Beschreib deinen Typ so genau, dass die Runde rät, wen aus dem Raum du meinst.', minPlayers: 3 },
  { text: 'Flüstere einer Person deiner Wahl etwas ins Ohr, das sonst niemand hören darf.' },
  { text: 'Nenne drei Dinge, die dich an einem Menschen sofort anziehen.' },
  { text: 'Such dir eine Person aus: 30 Sekunden Blickkontakt, kein Wort. Wer wegschaut, trinkt.' },
  { text: 'Zeig dein letztes Match – oder erzähl, warum es keines gibt.' },
  { text: 'Tanze 20 Sekunden so, als wolltest du genau eine Person beeindrucken.' },
  { text: 'Die Runde bestimmt, wem du ein ehrliches Kompliment machst. Du bestimmst welches.' },
  { text: 'Schreib jemandem aus deinen Kontakten eine ehrliche Nachricht. Die Runde liest nicht mit.' },
  { text: 'Verrate, wer hier den besten Flirt-Move hätte – und führ ihn vor.' },
  { text: 'Erzähl von deinem ersten Kuss. Alles, woran du dich erinnerst.' },
  { text: 'Sag der Person gegenüber einen Satz, der als Anmachspruch durchgehen würde.' },
].map((c) => ({ ...c, mode: 'pflicht', heat: 3, spicy: true }) as CardDef);

export const truthOrDare = createCardGame({
  ...meta,
  actor: 'turn',
  baseSips: 2,
  drink: 'none',
  resolveLabel: 'Gemacht',
  refuseLabel: 'Kneifen und trinken',
  refuseSips: 4,
  heatSelectable: true,
  cards: [...WAHRHEIT, ...PFLICHT, ...WAHRHEIT_SPICY, ...PFLICHT_SPICY],
});
